travis:
  secure:
    BINSTAR_TOKEN: XZT8d9Jq3COlB9WYS4HjTnvE3Dtbl69+HMlc3kD+dPzrs9F9pPYLNSfyIYyS/18gE/l1YrkaHkEXRswCvECUjzMesE3YVgeUaQ3qZf7UHs2OQoJZlXS6H1d6ieCDXl6ukM3RQ+nQcOd4iZfcVty9mZZVFgBrQuz5xKU4xoGTUdNNZsAXkYo/J8m0KvJBnonPt/kA5Zfrln5wLSQjiWeXt+wdM4rQ5llNQmbSp92Nq0zGGmXsVwpD2xESAih9igeVdRaa4TAhEUt6wNYCwpZTrfXNz0MTbhNTRqN81ltsMpN0k65GppTNQNbvTmcfJw7aS/tR6AQACxndKD5o7oB9TLwFcpnFkYfM5Jons8TbAdVRLHICf+IqV7j0rnF6fOSPVxGETHHsPhJmTSJfE2Ws3Baajsv8OjwM2sainte2TOGe/N8z4OmQmFouWJFy5AZK5TPUW40wLhVBLXQF87hlbDlBJmnOIiiTEfifSRgVkAEHHDVO563QZ8QotL+/3wwoWVblcLSKzWHvuky9aXTQYVskTeJXGSJl45mNAFkwrczoOhVi2/TFOplmqhwvUWTuAulq2KKk1XadQHPfsjuOx1Sf4OyGJETp8bXsvrxE05gY6hCzAnmr46v+3tTsHEyKemF/MW1MCIGLZNdtQ6G0TN0sbHk67wh4VcDCax7CHj8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
